### ISSUE TITLE
Need better logo

### ISSUE THREAD

**Issue by larsvilhuber** [social-science-data-editors/guidance#1]

**Comment by korenmiklos** [comment]
OK, posted a job on Fiverr.

**Comment by larsvilhuber** [comment]
That's an interesting idea...

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by korenmiklos** [comment]
![SSDE-logo](https://user-images.githubusercontent.com/1240330/55896071-c98e3f00-5bbd-11e9-8bac-d702eb34077b.jpeg)

**Comment by larsvilhuber** [comment]
Cool!

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
