### ISSUE TITLE
Suggested improvement: filter-branch for splitting repos

### ISSUE THREAD

**Issue by MichaelChirico** [social-science-data-editors/guidance#5]
I read this comment in the FAQ:

```
If not, then what I suggest is to do the following

clean up the repo (possibly in a branch)
on Github, there is no way to fork to your own space, and a fork would carry the entire history anyway. So this assumes manual interaction (I’m going to assume you use the command line for this, this works in git-bash, or bash on Linux/OSX).
create a new clone of your (now cleaned) repo, and switch to the clean branch ``` git clone (WHATEVER) cd whatever git branch “cleaned”

now wipe out all git information: ``` rm -rf .git

create a new repo ``` git init

Add all files ``` git add *
```

I think there are two things going on here, which can be handled differently:

1. Author wishes to wipe commit history (e.g. for privacy reasons). Then the advice above is most germane
2. Author keeps several papers related to an ongoing or long-running project in a single repo, and wants to isolate code for tidy submission alongside an "offshoot paper"

In the latter case, I'd recommend suggesting the `git filter-branch` approach, which is essentially a way to split off a subset of a repo into a new repo (e.g. a subdirectory `paper-1`). It will conveniently inherit the commit history as well. See guide:

https://help.github.com/en/articles/splitting-a-subfolder-out-into-a-new-repository

I think it would help if the FAQ delineated these two competing goals and stated more clearly the differences/approaches here.

**Comment by larsvilhuber** [comment]
Thank you, very good distinction. Will incorporate into next revision.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
